export default {
    SUCCEED_LOGIN: 'SUCCEED_LOGIN',
    FAIL_LOGIN: 'FAIL_LOGIN',
    LOG_OUT: 'LOG_OUT',
    FAIL_REQUEST: 'FAIL_REQUEST',
    ADD_FRIEND_ID: 'ADD_FRIEND_ID',

    GET_CHATS: 'GET_FRIENDS_LIST',
    START_CHAT: 'START_CHAT',
    CREATE_CHAT: 'CREATE_CHAT',

    GET_MESSAGES: 'GET_MESSAGESA',
    SEND_MESSAGE: 'SEND_MESSAGE',
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    
    SEARCH_FRIENDS: 'SEARCH_FRIENDS',
    
    GET_FRIEND_REQUESTS: 'GET_FRIEND_REQUESTS',
    RECEIVE_FRIEND_REQUEST: 'RECEIVE_FRIEND_REQUEST',
    ACCEPT_FRIEND_REQUEST: 'ACCEPT_FRIEND_REQUEST',
    REMOVE_FRIEND_REQIEST: 'REMOVE_FRIEND_REQIEST',
    
    LOAD_LOGIN_FINISH: 'LOAD_LOGIN_FINISH',
    LOAD_CHATS_FINISH: 'LOAD_CHATS_FINISH',
    LOAD_MESSAGES_INITIAL: 'LOAD_MESSAGES_INITIAL',
    LOAD_MESSAGES_FINISH: 'LOAD_MESSAGES_FINISH',
    SHOW_FRIEND_REQUESTS: 'SHOW_FRIEND_REQUESTS',
    SHOW_USER_OPERATION: 'SHOW_USER_OPERATION',
    SHOW_EMOJI: 'SHOW_EMOJI',
    SHOW_SEARCH_PEOPLE: 'SHOW_SEACH_PEOPLE'
};
